### ISSUE TITLE
svg-transform-loader stopped honoring -svg-height after upgrade from 1.0.2 to 1.2.1

### ISSUE THREAD

**Issue by iwaszko** [JetBrains/svg-mixer#38]
I've noticed that after upgrading `svg-transform-loader` from 1.0.2 to 1.2.1 SVGs have wrong sizes. 

I'm using `svg-transform-loader` with `postcss-loader` (3.0.0) and `postcss-move-props-to-bg-image-query` (0.2.5).

Here's a relevant part of my `webpack.config.js`:

```
{
  test: /\.svg(\?.*)?$/,
  use: [
    'url-loader',
    'svg-transform-loader'
  ]
},
```

`postcss.config.js`:
```
module.exports = {
  plugins: {
    'autoprefixer': {},
    'postcss-move-props-to-bg-image-query': {},
    'cssnano': {},
  }
};
```
and here's example CSS (using `@mdi/svg`):

```
.demo {
  height: 100px;
  background: #ffffe0 center no-repeat;
  background-image: url("~@mdi/svg/svg/alert.svg");
  -svg-fill: #ff0000;
  -svg-width: 50px;
  -svg-height: 50px;
}
```

Now, with 1.2.1 fill is applied but width and height are ignored. If I downgrade to 1.0.2, width and height are correct again.

What other info/samples would be helpful here?

**Comment by kisenka** [comment]
@iwaszko could you please provide the alert.svg content?

**Comment by iwaszko** [comment]
Sure, please find it below. On the other hand, this was just a demonstration as the problem seems to happen for all SVGs from https://www.npmjs.com/package/@mdi/svg that I've used.

```
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd"><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="24" height="24" viewBox="0 0 24 24"><path d="M13,14H11V10H13M13,18H11V16H13M1,21H23L12,2L1,21Z" /></svg>
```

**Comment by kisenka** [comment]
Ah, it was changing of default behaviour of posthtml-transform. Okay, I've published new major version 2.0.0 of svg-transform-loader which processes all nodes, including <svg> tag. As it behaves so, you should update you code in this way:

```css
.demo {
  background-image: url("~@mdi/svg/svg/alert.svg");
  -svg-fill: #ff0000; 

  /* you should specify selector to transform as second value to process only svg */
  -svg-width: 50px svg;

  /* and here too */
  -svg-height: 50px svg;
}
```
