### ISSUE TITLE
Is there any way to use CSS variables together with svg-transform-loader?

### ISSUE THREAD

**Issue by wujekbogdan** [JetBrains/svg-mixer#71]
When I do the following: 

``` css
.element {
  background-image: url('icon.svg');
  -svg-mixer-stroke: var(--my-custom-color-1);
}
```

then `var(--my-custom-color-1)` is not evaluated to an actual color.

I thought that maybe I could use the `transform` callback together with [postcss-css-variables](https://github.com/MadLittleMods/postcss-css-variables), but it's not possible because the css file is not available within the context of this callback.
